import { IDefaultQuoteItem, IProfileField } from '../../models/vendor-os/category-config.model';
import { PricingBasis, ResourceType } from '../../constants/vendorOs';

// Default CategoryConfig documents for the 8 launch categories — spec
// section 5 transcribed field-for-field. Seeded (insert-if-missing, never
// overwritten) by CategoryConfigService.ensureDefaults, after which the
// admin console owns them.

export interface CategoryConfigSeed {
  key: string;
  name: string;
  icon: string;
  pricingBasis: PricingBasis;
  resourceType: ResourceType;
  defaultResourceName: string;
  defaultResourceCapacity: number;
  softBlockDayBefore?: boolean;
  marketplaceCategorySlug?: string;
  subTagOptions: string[];
  profileSchema: IProfileField[];
  defaultQuoteItems: IDefaultQuoteItem[];
  defaultDeliverables: string[];
  defaultTerms: string;
  defaultFaqs: string[];
}

const COMMON_TERMS =
  'Date is blocked only after the advance is received. Advance is non-refundable. Balance as per the payment schedule. Prices exclude GST unless stated.';

export const CATEGORY_CONFIG_SEEDS: CategoryConfigSeed[] = [
  {
    key: 'venue',
    name: 'Venues & banquets',
    icon: '🏛️',
    pricingBasis: 'per_day',
    resourceType: 'space_slot',
    defaultResourceName: 'Main hall',
    defaultResourceCapacity: 1,
    marketplaceCategorySlug: 'venue',
    subTagOptions: ['Palace lawn', 'Banquet hall', 'Farmhouse', 'Hotel', 'Destination resort', 'Community hall'],
    profileSchema: [
      { key: 'venueType', label: 'Venue type', type: 'select', options: ['Palace lawn', 'Banquet hall', 'Farmhouse', 'Hotel', 'Destination resort', 'Community hall'], required: true, group: 'Basics' },
      { key: 'indoorCapacitySeated', label: 'Indoor capacity (seated)', type: 'number', group: 'Capacity' },
      { key: 'indoorCapacityFloating', label: 'Indoor capacity (floating)', type: 'number', group: 'Capacity' },
      { key: 'outdoorCapacitySeated', label: 'Outdoor capacity (seated)', type: 'number', group: 'Capacity' },
      { key: 'outdoorCapacityFloating', label: 'Outdoor capacity (floating)', type: 'number', group: 'Capacity' },
      { key: 'spacesCount', label: 'Number of halls/lawns', type: 'number', required: true, group: 'Capacity' },
      { key: 'roomsOnSite', label: 'Rooms on-site', type: 'number', group: 'Stay' },
      { key: 'roomTariff', label: 'Room tariff (per night)', type: 'number', unit: 'INR', group: 'Stay' },
      { key: 'complimentaryRooms', label: 'Complimentary rooms', type: 'number', group: 'Stay' },
      { key: 'parkingCapacity', label: 'Parking capacity (cars)', type: 'number', group: 'Facilities' },
      { key: 'cateringPolicy', label: 'Catering policy', type: 'select', options: ['In-house only', 'Empanelled caterers', 'Outside allowed with royalty', 'Outside allowed'], required: true, group: 'Policies' },
      { key: 'decorPolicy', label: 'Decor policy', type: 'select', options: ['In-house only', 'Outside allowed'], group: 'Policies' },
      { key: 'alcoholPolicy', label: 'Alcohol policy & licence', type: 'text', group: 'Policies' },
      { key: 'musicCurfew', label: 'DJ / music curfew time', type: 'text', group: 'Policies' },
      { key: 'powerBackup', label: 'Power backup', type: 'boolean', group: 'Facilities' },
      { key: 'airConditioned', label: 'AC', type: 'select', options: ['AC', 'Non-AC', 'Both'], group: 'Facilities' },
      { key: 'changingRooms', label: 'Changing rooms', type: 'number', group: 'Facilities' },
      { key: 'mandapArea', label: 'Mandap area', type: 'text', group: 'Facilities' },
      { key: 'accessibility', label: 'Accessibility', type: 'text', group: 'Facilities' },
      { key: 'nearestAirportKm', label: 'Nearest airport (km)', type: 'number', group: 'Location' },
      { key: 'nearestRailwayKm', label: 'Nearest railway station (km)', type: 'number', group: 'Location' },
      { key: 'vegPlateRate', label: 'Veg per-plate rate (if in-house catering)', type: 'number', unit: 'INR', group: 'Pricing' },
      { key: 'nonVegPlateRate', label: 'Non-veg per-plate rate', type: 'number', unit: 'INR', group: 'Pricing' },
      { key: 'minimumGuaranteePlates', label: 'Minimum guarantee (plates)', type: 'number', group: 'Pricing' },
    ],
    defaultQuoteItems: [
      { name: 'Space rental', unit: 'day', qty: 1, taxPercent: 18 },
      { name: 'Per-plate catering', unit: 'plate', qty: 300, taxPercent: 5 },
      { name: 'Rooms', unit: 'room-night', qty: 10, taxPercent: 12 },
      { name: 'Extra hours', unit: 'hour', qty: 0, taxPercent: 18 },
      { name: 'Security & cleaning', unit: 'lot', qty: 1, taxPercent: 18 },
      { name: 'Royalty for outside caterer/decorator', unit: 'lot', qty: 0, taxPercent: 18 },
    ],
    defaultDeliverables: ['Venue access from 8 AM to midnight', 'Power backup', 'Changing rooms'],
    defaultTerms: COMMON_TERMS,
    defaultFaqs: ['Is outside catering allowed?', 'What is the music curfew time?', 'Are rooms included?'],
  },
  {
    key: 'photography',
    name: 'Photography & films',
    icon: '📷',
    pricingBasis: 'per_day',
    resourceType: 'crew',
    defaultResourceName: 'Crew A',
    defaultResourceCapacity: 1,
    marketplaceCategorySlug: 'photographers',
    subTagOptions: ['Candid', 'Traditional', 'Cinematic', 'Documentary', 'Editorial', 'Drone', 'Pre-wedding', 'Live streaming'],
    profileSchema: [
      { key: 'styles', label: 'Style', type: 'multiselect', options: ['Candid', 'Traditional', 'Cinematic', 'Documentary', 'Editorial'], required: true, group: 'Basics' },
      { key: 'services', label: 'Services', type: 'multiselect', options: ['Photo', 'Video', 'Drone', 'Same-day edit', 'Pre-wedding', 'Live streaming', 'Photobooth'], required: true, group: 'Basics' },
      { key: 'teamPerDay', label: 'Team composition per day', type: 'text', group: 'Team' },
      { key: 'equipment', label: 'Equipment highlights', type: 'textarea', group: 'Team' },
      { key: 'editedPhotosCount', label: 'Edited photos delivered', type: 'number', group: 'Deliverables' },
      { key: 'rawFiles', label: 'Raw files provided', type: 'boolean', group: 'Deliverables' },
      { key: 'albumPages', label: 'Album pages', type: 'number', group: 'Deliverables' },
      { key: 'filmLengthMinutes', label: 'Film length (minutes)', type: 'number', group: 'Deliverables' },
      { key: 'teaser', label: 'Teaser included', type: 'boolean', group: 'Deliverables' },
      { key: 'deliveryWeeks', label: 'Delivery timeline (weeks)', type: 'number', required: true, group: 'Deliverables' },
      { key: 'travelTerms', label: 'Travel & stay terms', type: 'textarea', group: 'Travel' },
      { key: 'destinationExperience', label: 'Destination wedding experience', type: 'boolean', group: 'Travel' },
    ],
    defaultQuoteItems: [
      { name: 'Wedding coverage (team per day)', unit: 'day', qty: 2, taxPercent: 18 },
      { name: 'Drone coverage', unit: 'day', qty: 1, taxPercent: 18 },
      { name: 'Album', unit: 'album', qty: 1, taxPercent: 18 },
      { name: 'Pre-wedding shoot', unit: 'shoot', qty: 1, taxPercent: 18 },
      { name: 'Travel', unit: 'lot', qty: 0, taxPercent: 18 },
      { name: 'Stay', unit: 'night', qty: 0, taxPercent: 18 },
    ],
    defaultDeliverables: ['Edited photos in online gallery', 'Highlight film', 'Teaser within 7 days', 'Album design with 2 revisions'],
    defaultTerms: COMMON_TERMS,
    defaultFaqs: ['Do you provide raw files?', 'How long does delivery take?', 'Do you travel for destination weddings?'],
  },
  {
    key: 'catering',
    name: 'Catering & cuisine',
    icon: '🍽️',
    pricingBasis: 'per_plate',
    resourceType: 'capacity',
    defaultResourceName: 'Kitchen capacity (pax)',
    defaultResourceCapacity: 1000,
    marketplaceCategorySlug: 'food',
    subTagOptions: ['Rajasthani', 'North Indian', 'South Indian', 'Chinese', 'Continental', 'Italian', 'Chaat', 'Street food'],
    profileSchema: [
      { key: 'cuisines', label: 'Cuisines', type: 'multiselect', options: ['Rajasthani', 'North Indian', 'South Indian', 'Chinese', 'Continental', 'Italian', 'Chaat', 'Street food'], required: true, group: 'Menu' },
      { key: 'dietary', label: 'Dietary', type: 'multiselect', options: ['Pure veg', 'Non-veg', 'Jain', 'Vegan', 'Satvik', 'No onion-garlic'], required: true, group: 'Menu' },
      { key: 'liveCounters', label: 'Live counters offered', type: 'tags', group: 'Menu' },
      { key: 'minPax', label: 'Minimum pax', type: 'number', required: true, group: 'Capacity' },
      { key: 'maxPax', label: 'Maximum pax', type: 'number', required: true, group: 'Capacity' },
      { key: 'serviceStyle', label: 'Service style', type: 'multiselect', options: ['Buffet', 'Plated', 'Family-style', 'Food trucks'], group: 'Service' },
      { key: 'waitersPer100', label: 'Waiters per 100 guests', type: 'number', group: 'Service' },
      { key: 'crockeryIncluded', label: 'Crockery & cutlery included', type: 'boolean', group: 'Service' },
      { key: 'kitchenSetup', label: 'Kitchen', type: 'select', options: ['Own kitchen setup', 'Needs venue kitchen'], group: 'Service' },
      { key: 'fssaiLicence', label: 'FSSAI licence number', type: 'text', required: true, group: 'Compliance' },
      { key: 'barService', label: 'Bar service', type: 'boolean', group: 'Service' },
      { key: 'tastingPolicy', label: 'Tasting session policy', type: 'text', group: 'Service' },
    ],
    defaultQuoteItems: [
      { name: 'Menu (per plate)', unit: 'plate', qty: 300, taxPercent: 5 },
      { name: 'Live counters', unit: 'counter', qty: 2, taxPercent: 5 },
      { name: 'Extra plates', unit: 'plate', qty: 0, taxPercent: 5 },
      { name: 'Service staff', unit: 'staff', qty: 10, taxPercent: 18 },
      { name: 'Transport', unit: 'lot', qty: 1, taxPercent: 18 },
      { name: 'Tasting session', unit: 'session', qty: 1, taxPercent: 5 },
    ],
    defaultDeliverables: ['Crockery & cutlery', 'Uniformed service staff', 'Buffet setup'],
    defaultTerms: `${COMMON_TERMS} Final guest count to be confirmed 7 days before the event; minimum guarantee applies.`,
    defaultFaqs: ['Is a tasting session available?', 'Do you serve Jain food?', 'What is the minimum guarantee?'],
  },
  {
    key: 'decor',
    name: 'Decor & florists',
    icon: '🌸',
    pricingBasis: 'per_function',
    resourceType: 'crew',
    defaultResourceName: 'Setup crew A',
    defaultResourceCapacity: 1,
    softBlockDayBefore: true,
    marketplaceCategorySlug: 'planning-decor',
    subTagOptions: ['Mandap', 'Floral installations', 'Stage', 'Entrance', 'Lighting', 'Tenting', 'Furniture', 'Themed sets'],
    profileSchema: [
      { key: 'specialities', label: 'Specialities', type: 'multiselect', options: ['Mandap', 'Floral installations', 'Stage', 'Entrance', 'Lighting', 'Tenting', 'Furniture', 'Themed sets'], required: true, group: 'Basics' },
      { key: 'flowerTypes', label: 'Flower types', type: 'multiselect', options: ['Fresh', 'Artificial', 'Mixed', 'Imported'], group: 'Basics' },
      { key: 'inHouseFabrication', label: 'In-house fabrication & lighting', type: 'boolean', group: 'Capability' },
      { key: 'teamSize', label: 'Team size', type: 'number', group: 'Capability' },
      { key: 'setupTimeHours', label: 'Setup time needed (hours)', type: 'number', group: 'Capability' },
      { key: 'designConsultation', label: 'Design consultation included', type: 'boolean', group: 'Design' },
      { key: 'renderProvided', label: '3D render / mood board provided', type: 'boolean', group: 'Design' },
    ],
    defaultQuoteItems: [
      { name: 'Mandap (material + labour)', unit: 'function', qty: 1, taxPercent: 18 },
      { name: 'Stage', unit: 'function', qty: 1, taxPercent: 18 },
      { name: 'Entrance', unit: 'function', qty: 1, taxPercent: 18 },
      { name: 'Seating', unit: 'function', qty: 1, taxPercent: 18 },
      { name: 'Lighting', unit: 'function', qty: 1, taxPercent: 18 },
      { name: 'Floral', unit: 'function', qty: 1, taxPercent: 18 },
    ],
    defaultDeliverables: ['Mood board before booking', 'Setup a day before', 'Teardown the morning after'],
    defaultTerms: COMMON_TERMS,
    defaultFaqs: ['Do you use fresh flowers?', 'Do you provide a 3D render?', 'How early do you set up?'],
  },
  {
    key: 'makeup',
    name: 'Mehendi & makeup',
    icon: '💄',
    pricingBasis: 'per_face',
    resourceType: 'artist_slot',
    defaultResourceName: 'Lead artist',
    defaultResourceCapacity: 1,
    marketplaceCategorySlug: 'makeup',
    subTagOptions: ['Bridal makeup', 'Party makeup', 'HD', 'Airbrush', 'Hairstyling', 'Draping', 'Bridal mehendi', 'Guest mehendi', 'Nail art'],
    profileSchema: [
      { key: 'services', label: 'Services', type: 'multiselect', options: ['Bridal makeup', 'Engagement/party makeup', 'HD', 'Airbrush', 'Hairstyling', 'Draping', 'Mehendi bridal', 'Mehendi guest', 'Nail art'], required: true, group: 'Basics' },
      { key: 'brands', label: 'Products / brands used', type: 'tags', group: 'Basics' },
      { key: 'trialPolicy', label: 'Trial policy', type: 'text', group: 'Policies' },
      { key: 'trialCharge', label: 'Trial charge', type: 'number', unit: 'INR', group: 'Policies' },
      { key: 'travel', label: 'Travel to venue', type: 'select', options: ['City only', 'Outstation too'], group: 'Policies' },
      { key: 'teamSize', label: 'Team size (for guest makeup/mehendi)', type: 'number', group: 'Team' },
      { key: 'mehendiStyles', label: 'Mehendi style', type: 'multiselect', options: ['Rajasthani', 'Arabic', 'Minimal', 'Portrait'], group: 'Mehendi' },
      { key: 'hoursPerBridalLook', label: 'Time per bridal look (hours)', type: 'number', group: 'Basics' },
      { key: 'earlyMorningSurcharge', label: 'Early-morning surcharge', type: 'number', unit: 'INR', group: 'Policies' },
    ],
    defaultQuoteItems: [
      { name: 'Bridal look', unit: 'look', qty: 1, taxPercent: 18 },
      { name: 'Family makeup', unit: 'face', qty: 4, taxPercent: 18 },
      { name: 'Guest makeup', unit: 'hour', qty: 0, taxPercent: 18 },
      { name: 'Bridal mehendi (hands + feet)', unit: 'set', qty: 1, taxPercent: 18 },
      { name: 'Trial', unit: 'trial', qty: 1, taxPercent: 18 },
      { name: 'Travel', unit: 'lot', qty: 0, taxPercent: 18 },
    ],
    defaultDeliverables: ['Premium products', 'Hairstyling & draping', 'Touch-up kit'],
    defaultTerms: COMMON_TERMS,
    defaultFaqs: ['Is a trial included?', 'Which brands do you use?', 'Do you travel to the venue?'],
  },
  {
    key: 'music',
    name: 'Music, DJ & dhol',
    icon: '🥁',
    pricingBasis: 'per_function',
    resourceType: 'artist_slot',
    defaultResourceName: 'Main set',
    defaultResourceCapacity: 1,
    marketplaceCategorySlug: 'music-dance',
    subTagOptions: ['DJ', 'Live band', 'Sufi/ghazal', 'Dhol troupe', 'Nagada', 'Shehnai', 'Sangeet choreographer', 'Anchor/emcee'],
    profileSchema: [
      { key: 'type', label: 'Type', type: 'multiselect', options: ['DJ', 'Live band', 'Sufi/ghazal', 'Dhol troupe', 'Nagada', 'Shehnai', 'Sangeet choreographer', 'Anchor/emcee'], required: true, group: 'Basics' },
      { key: 'genres', label: 'Genres', type: 'tags', group: 'Basics' },
      { key: 'soundSetup', label: 'Sound setup (watts, brand)', type: 'text', group: 'Setup' },
      { key: 'lighting', label: 'Lighting / LED wall / trussing', type: 'text', group: 'Setup' },
      { key: 'artistsCount', label: 'Number of artists / dhol players', type: 'number', group: 'Team' },
      { key: 'choreographySessions', label: 'Choreography sessions included', type: 'number', group: 'Sangeet' },
      { key: 'performancesCount', label: 'Number of performances', type: 'number', group: 'Sangeet' },
      { key: 'ownGenerator', label: 'Own generator', type: 'boolean', group: 'Setup' },
      { key: 'licenceStatus', label: 'Licence (PPL/IPRS) status', type: 'text', group: 'Compliance' },
      { key: 'outstationTerms', label: 'Outstation terms', type: 'text', group: 'Travel' },
    ],
    defaultQuoteItems: [
      { name: 'Base performance', unit: 'function', qty: 1, taxPercent: 18 },
      { name: 'Extra hours', unit: 'hour', qty: 0, taxPercent: 18 },
      { name: 'Additional artists', unit: 'artist', qty: 0, taxPercent: 18 },
      { name: 'Sound & light rig', unit: 'lot', qty: 1, taxPercent: 18 },
      { name: 'Generator', unit: 'lot', qty: 0, taxPercent: 18 },
      { name: 'Choreography sessions', unit: 'session', qty: 0, taxPercent: 18 },
    ],
    defaultDeliverables: ['4 hours performance', 'Sound check before the event'],
    defaultTerms: COMMON_TERMS,
    defaultFaqs: ['How many hours is the base performance?', 'Do you bring your own generator?'],
  },
  {
    key: 'transport',
    name: 'Transport & baraat',
    icon: '🚗',
    pricingBasis: 'per_vehicle',
    resourceType: 'inventory',
    defaultResourceName: 'Vehicle 1',
    defaultResourceCapacity: 1,
    subTagOptions: ['Vintage cars', 'Luxury cars', 'Baggi', 'Ghodi', 'Camel', 'Guest coaches', 'Tempo travellers', 'Valet'],
    profileSchema: [
      { key: 'fleet', label: 'Fleet types', type: 'multiselect', options: ['Vintage cars', 'Luxury cars', 'Buggy/baggi', 'Ghodi/horse', 'Elephant', 'Camel', 'Guest coaches', 'Tempo travellers', 'Valet service'], required: true, group: 'Fleet' },
      { key: 'fleetDetails', label: 'Per-vehicle details (make, model, year, colour, seating)', type: 'textarea', group: 'Fleet' },
      { key: 'driverIncluded', label: 'Driver included', type: 'boolean', group: 'Terms' },
      { key: 'kmLimit', label: 'Km limit per day', type: 'number', group: 'Terms' },
      { key: 'extraKmRate', label: 'Extra km rate', type: 'number', unit: 'INR', group: 'Terms' },
      { key: 'decorationIncluded', label: 'Decoration included', type: 'boolean', group: 'Terms' },
      { key: 'outstation', label: 'Outstation available', type: 'boolean', group: 'Terms' },
      { key: 'insurancePermits', label: 'Insurance & permits', type: 'text', group: 'Compliance' },
    ],
    defaultQuoteItems: [
      { name: 'Vehicle', unit: 'day', qty: 1, taxPercent: 18 },
      { name: 'Decoration', unit: 'vehicle', qty: 1, taxPercent: 18 },
      { name: 'Driver', unit: 'day', qty: 1, taxPercent: 18 },
      { name: 'Extra km', unit: 'km', qty: 0, taxPercent: 18 },
      { name: 'Valet attendants', unit: 'attendant', qty: 0, taxPercent: 18 },
      { name: 'Guest coaches', unit: 'trip', qty: 0, taxPercent: 18 },
    ],
    defaultDeliverables: ['Decorated vehicle', 'Uniformed driver'],
    defaultTerms: COMMON_TERMS,
    defaultFaqs: ['Is decoration included?', 'What is the km limit?'],
  },
  {
    key: 'invitations',
    name: 'Invitations & gifting',
    icon: '💌',
    pricingBasis: 'per_card',
    resourceType: 'production_date',
    defaultResourceName: 'Production capacity (units/day)',
    defaultResourceCapacity: 1000,
    marketplaceCategorySlug: 'invites-gifts',
    subTagOptions: ['Printed cards', 'Boxed invites', 'Digital invites', 'Video invites', 'Trousseau packing', 'Favours', 'Hampers', 'Sweets boxes'],
    profileSchema: [
      { key: 'products', label: 'Products', type: 'multiselect', options: ['Printed cards', 'Boxed invites', 'Digital invites/e-cards', 'Video invites', 'Trousseau packing', 'Favours', 'Hampers', 'Sweets boxes'], required: true, group: 'Basics' },
      { key: 'printingTypes', label: 'Printing types', type: 'multiselect', options: ['Offset', 'Letterpress', 'Foil', 'Laser cut', 'Acrylic'], group: 'Basics' },
      { key: 'moq', label: 'Minimum order quantity', type: 'number', required: true, group: 'Orders' },
      { key: 'designIncluded', label: 'Design', type: 'select', options: ['Included', 'Charged'], group: 'Orders' },
      { key: 'turnaroundDays', label: 'Turnaround time (days)', type: 'number', required: true, group: 'Orders' },
      { key: 'samplePolicy', label: 'Sample policy', type: 'text', group: 'Orders' },
      { key: 'panIndiaShipping', label: 'Ships pan-India', type: 'boolean', group: 'Orders' },
      { key: 'customisation', label: 'Customisation (languages, motifs, crests)', type: 'tags', group: 'Basics' },
    ],
    defaultQuoteItems: [
      { name: 'Invitation cards', unit: 'card', qty: 300, taxPercent: 12 },
      { name: 'Design fee', unit: 'lot', qty: 1, taxPercent: 18 },
      { name: 'Inserts', unit: 'card', qty: 0, taxPercent: 12 },
      { name: 'Envelopes & boxes', unit: 'unit', qty: 300, taxPercent: 12 },
      { name: 'Favours', unit: 'unit', qty: 0, taxPercent: 12 },
      { name: 'Shipping', unit: 'lot', qty: 1, taxPercent: 18 },
    ],
    defaultDeliverables: ['Digital proof before printing', 'Two design revisions'],
    defaultTerms: `${COMMON_TERMS} Printing starts only after final proof approval.`,
    defaultFaqs: ['What is the minimum order?', 'How long does printing take?', 'Do you ship pan-India?'],
  },
];
